apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.appName }}-service
  namespace: {{ .Release.Namespace }}
spec:
  gateways:
  -  istio-system/public-gateway
  hosts:
    - {{ .Values.appName }}-{{ .Release.Namespace }}.{{ .Values.domainName }}
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: {{ .Values.appName }}.{{ .Release.Namespace }}.svc.cluster.local
        port:
          number: {{ .Values.service.port }}
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.appName }}-storybook-service
  namespace: {{ .Release.Namespace }}
spec:
  gateways:
  -  istio-system/public-gateway
  hosts:
    - {{ .Values.appName }}-storybook-{{ .Release.Namespace }}.{{ .Values.domainName }}
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: {{ .Values.appName }}-storybook.{{ .Release.Namespace }}.svc.cluster.local
        port:
          number: {{ .Values.service.portStorybook }}
